apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: simarsaggu99
        image: gcr.io/sit737-24t1-simardeep-c8dc608/nodejs-app:v1
        ports:
        - containerPort: 80